/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ConsultationItem = ({ number, title, responses }) => {
  return (
    <article className="consultation-item">
      <span className="consultation-number">{number}</span>
      <div className="consultation-content">
        <h3 className="consultation-title">{title}</h3>
        <p className="consultation-responses">{responses} réponses</p>
      </div>
    </article>
  );
};

export default ConsultationItem;
