/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Footer = () => {
  return (
    <footer className="main-footer">
      <div className="footer-content">
        <div className="footer-section">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/0f9bc6aae80fcabc97dba7a9e4645b4fbf0e9097b386769bf4abce07c6455680?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
            alt="Company Logo"
            className="footer-logo"
          />
          <nav className="footer-nav">
            <a href="#about">À propos</a>
            <a href="#legal">Mentions légales</a>
            <a href="#privacy">Protection des données</a>
            <a href="#advertising">Politique publicitaire</a>
            <a href="#cookies">Politique de cookies</a>
            <a href="#results">Comment nous vous montrons les résultats</a>
            <a href="#opinions">Opinions</a>
          </nav>
          <nav className="footer-nav">
            <a href="#premium">Plan Premium</a>
            <a href="#add-office">Ajoutez votre cabinet</a>
            <a href="#pro-login">Connexion professionnels</a>
            <a href="#advertise">Annoncez-vous</a>
            <a href="#help">Avez-vous besoin d'aide ?</a>
          </nav>
        </div>
        <div className="footer-section">
          <h3>Derniers cabinets</h3>
          <ul className="recent-offices">
            <li>Veronique Macheix</li>
            <li>Nadra Rouzeik</li>
            <li>Gilles de la Londe Aurore</li>
            <li>Julia Radoszycki</li>
            <li>Ludivine Noirault</li>
          </ul>
          <h3>Top villes</h3>
          <ul className="top-cities">
            <li>Psychologues Paris</li>
            <li>Psychologues Gironde</li>
            <li>Psychologues Bouches-du-Rhône</li>
            <li>Psychologues Rhône</li>
            <li>Psychologues Haute-Garonne</li>
          </ul>
          <h3>Dernières recherches</h3>
          <ul className="recent-searches">
            <li>Psychothérapie</li>
            <li>Psychologie enfant</li>
            <li>Psychanalyse</li>
            <li>Thérapie de couple</li>
          </ul>
        </div>
      </div>
      <div className="social-links">
        <span>Suivez-nous:</span>
        <a href="#facebook" aria-label="Facebook">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/14894cbd93814b5f4b62c34d7b8cd7adc15f22f99043800556e1ec6dfcde104c?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
            alt=""
            className="social-icon"
          />
        </a>
        <a href="#twitter" aria-label="Twitter">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/63fd1dd0df22538695df08b3663712387e35bc9637f0702d10a93877265d7e4b?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
            alt=""
            className="social-icon"
          />
        </a>
      </div>
      <div className="copyright">
        © 2005 - 2024 GoodMental.fr Tous droits réservés. Mise à jour: October
        2024
      </div>
    </footer>
  );
};

export default Footer;
