/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Hero = () => {
  return (
    <section className="hero">
      <h1 className="hero-title">Découvrez nos différents questionnaires</h1>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/a6999b61d92036781104055acadac01a5b61aafa8975e49ed249a09a0a0b0323?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
        alt="Background image for hero section"
        className="hero-background"
      />
    </section>
  );
};

export default Hero;
