/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Navigation = () => {
  return (
    <nav className="main-navigation">
      <ul className="nav-list">
        <li>
          <a href="#questionnaires">Nos questionnaires</a>
        </li>
        <li>
          <a href="#chat">Chat</a>
        </li>
        <li>
          <a href="#dashboard">Dashboard</a>
        </li>
        <li>
          <a href="#notification">Notification</a>
        </li>
        <li>
          <a href="#faq">FAQ</a>
        </li>
        <li>
          <a href="#about">A propos</a>
        </li>
      </ul>
      <div className="professional-space">
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/13774ea6022b4fe0939e748c15e8d8a1b713b571c456c16ecb24a4e2d531808b?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
          alt=""
          className="icon"
        />
        <span>Espace professionnel</span>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/d9773e431bd730a0d6631611d8b0ab2a3fce48ad5034a65b80c82ef8952a3ae9?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
          alt=""
          className="icon"
        />
      </div>
    </nav>
  );
};

export default Navigation;
