/**
 * This code was generated by Builder.io.
 */
import React from "react";

const QuestionnaireCard = ({ title, description, ctaText, tags }) => {
  return (
    <article className="questionnaire-card">
      <div className="card-content">
        <h3 className="card-title">{title}</h3>
        <p className="card-description">{description}</p>
        <a href="#start-test" className="cta-button">
          {ctaText}
        </a>
      </div>
      <div className="card-tags">
        {tags.map((tag, index) => (
          <span key={index} className="tag">
            {tag}
          </span>
        ))}
      </div>
    </article>
  );
};

export default QuestionnaireCard;
