/**
 * This code was generated by Builder.io.
 */
import React from "react";
import QuestionnaireCard from "./QuestionnaireCard";

const RecommendedQuestionnaires = () => {
  const questionnaires = [
    {
      title: "Test de bien-être",
      description: "évaluer votre bien-être mental grâce a nos test !",
      ctaText: "Commencer le test",
      tags: ["RAPIDE", "MOYEN", "POUSSE"],
    },
  ];

  return (
    <section className="recommended-questionnaires">
      <h2 className="section-title">Les questionnaires recommandés</h2>
      <p className="section-description">
        Thérapies les plus demandées par les utilisateurs.
      </p>
      <div className="questionnaire-list">
        {questionnaires.map((questionnaire, index) => (
          <QuestionnaireCard key={index} {...questionnaire} />
        ))}
      </div>
      <a href="#all-questionnaires" className="see-all-link">
        Voir Tous
      </a>
    </section>
  );
};

export default RecommendedQuestionnaires;
