/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ConsultationItem from "./ConsultationItem";

const TopConsultations = () => {
  const consultations = [
    {
      number: 1,
      title: "Mon fils de 14 ans a fait des attouchements sexuels",
      responses: 21,
    },
    {
      number: 2,
      title: "Quelle est la différence entre un psychologue et un psychiatre ?",
      responses: 13,
    },
    {
      number: 3,
      title: "Rêves et lieu : maison familiale ou maison d'enfance récurrente",
      responses: 11,
    },
    {
      number: 4,
      title:
        "Bonjour, que pensez vous d'un pere qui dort avec sa fille de 10 an…",
      responses: 22,
    },
    {
      number: 5,
      title: "Différence psychologie etpsychanalyse",
      responses: 12,
    },
    {
      number: 6,
      title: "Est-ce que mon professeur est attiré par moi ?",
      responses: 12,
    },
  ];

  return (
    <section className="top-consultations">
      <h2 className="section-title">Top Consultations</h2>
      <p className="section-description">
        <strong>Posez vos questions à un </strong>
        <span className="highlight">psy</span>
        <strong> et faites le premier pas en regardant les </strong>
        <span className="highlight">questions</span>
        <strong> d'autres utilisateurs.</strong>
      </p>
      <div className="consultation-list">
        {consultations.map((consultation, index) => (
          <ConsultationItem key={index} {...consultation} />
        ))}
      </div>
      <a href="#all-consultations" className="see-all-link">
        Voir tous
      </a>
    </section>
  );
};

export default TopConsultations;
