/**
 * This code was generated by Builder.io.
 */
import React from "react";
import "./Footer.css";

function Footer() {
  return (
    <footer className="main-footer">
      <div className="footer-content">
        <div className="footer-section">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/0f9bc6aae80fcabc97dba7a9e4645b4fbf0e9097b386769bf4abce07c6455680?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
            alt="Logo"
            className="footer-logo"
          />
          <nav className="footer-nav">
            <a href="#">À propos</a>
            <a href="#">Mentions légales</a>
            <a href="#">Protection des données</a>
            <a href="#">Politique publicitaire</a>
            <a href="#">Politique de cookies</a>
            <a href="#">Comment nous vous montrons les résultats</a>
            <a href="#">Opinions</a>
          </nav>
        </div>
        <div className="footer-section">
          <h3>Plan Premium</h3>
          <nav className="footer-nav">
            <a href="#">Ajoutez votre cabinet</a>
            <a href="#">Connexion professionnels</a>
            <a href="#">Annoncez-vous</a>
            <a href="#">Avez-vous besoin d'aide ?</a>
          </nav>
        </div>
        <div className="footer-section">
          <h3>Derniers cabinets</h3>
          <ul className="recent-cabinets">
            <li>Veronique Macheix</li>
            <li>Nadra Rouzeik</li>
            <li>Gilles de la Londe Aurore</li>
            <li>Julia Radoszycki</li>
            <li>Ludivine Noirault</li>
          </ul>
        </div>
        <div className="footer-section">
          <h3>Top villes</h3>
          <ul className="top-cities">
            <li>Psychologues Paris</li>
            <li>Psychologues Gironde</li>
            <li>Psychologues Bouches-du-Rhône</li>
            <li>Psychologues Rhône</li>
            <li>Psychologues Haute-Garonne</li>
          </ul>
        </div>
      </div>
      <div className="footer-bottom">
        <p>Suivez-nous:</p>
        <div className="social-links">
          <a href="#" aria-label="Facebook">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/14894cbd93814b5f4b62c34d7b8cd7adc15f22f99043800556e1ec6dfcde104c?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
              alt=""
              className="social-icon"
            />
          </a>
          <a href="#" aria-label="Twitter">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/63fd1dd0df22538695df08b3663712387e35bc9637f0702d10a93877265d7e4b?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
              alt=""
              className="social-icon"
            />
          </a>
        </div>
      </div>
      <div className="copyright">
        © 2005 - 2024 GoodMental.fr Tous droits réservés. Mise à jour: October
        2024
      </div>
    </footer>
  );
}

export default Footer;
