/**
 * This code was generated by Builder.io.
 */
import React from "react";
import "./Header.css";

function Header() {
  return (
    <header className="main-header">{/* Header content goes here */}</header>
  );
}

export default Header;
