/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import QuestionnaireSection from "./QuestionnaireSection";
import TopConsultationsSection from "./TopConsultationsSection";
import PsychologyNewsSection from "./PsychologyNewsSection";
import SpecialistSearchSection from "./SpecialistSearchSection";
import Footer from "./Footer";
import "./HomePage.css";

function HomePageAcceuille() {
  return (
    <div className="home-page">
      <Header />
      <main>
        <section className="hero-section">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/a6999b61d92036781104055acadac01a5b61aafa8975e49ed249a09a0a0b0323?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
            alt=""
            className="hero-image"
          />
          <h1 className="hero-title">
            Découvrez nos différents questionnaires
          </h1>
        </section>
        <QuestionnaireSection />
        <TopConsultationsSection />
        <PsychologyNewsSection />
        <SpecialistSearchSection />
      </main>
      <Footer />
    </div>
  );
}

export default HomePageAcceuille;
