/**
 * This code was generated by Builder.io.
 */
import React from "react";
import "./PsychologyNewsSection.css";

function PsychologyNewsSection() {
  const newsArticles = [
    {
      id: 1,
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/b0d46eb640d8860e6982f61dc444572c5585287cbe7d8b57f12dcaa6faf4c222?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae",
      category: "Aptitudes sociales",
      title:
        "Masking : masquer nos symptômes pour que nous puissions nous intégrer",
    },
    {
      id: 2,
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/1662c540fe9f89687d1ddbcec88dfcbcea9b924d63545e2307bc9b781872e73a?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae",
      category: "Dépression",
      title:
        "Pourquoi est-ce que je me sens vide dans ma vie ? 6 raisons et comment …",
    },
    {
      id: 3,
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/cb0c3486c43812aea5f83abe231d6be0c3e355a5d82c78098fd03e0a39bea44c?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae",
      category: "Dépression",
      title:
        "Prévention du suicide : 10 conseils pour aider un ami ou un membre de …",
    },
    {
      id: 4,
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/fc48faca93bd97cb1bbfead52b63ccb24b4618a7a65e4dfba1a14ff54cd0b0a7?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae",
      category: "Dépression",
      title: "Psychothérapie du suicide : 5 thérapies efficaces pour sa…",
    },
    {
      id: 5,
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/a9111fe3336cb31a5e1d3089a31da4b79a407b2d96959d144d51fb7db491d263?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae",
      category: "Crise existentielle",
      title:
        "Comment trouver sa place dans le monde ? 7 façons de vous connecte…",
    },
    {
      id: 6,
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/18dac640f499fbcf4e0acf781f43ccc5777ee6d73e45e42b31b9854504e5891d?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae",
      category: "Psychologie travail",
      title:
        "Comment trouver le bonheur au travail ? 8 conseils pour y parvenir",
    },
  ];

  return (
    <section className="psychology-news-section">
      <h2 className="section-title">Actualité Psychologie</h2>
      <p className="section-description">
        <strong>Derniers articles publiés sur l'actualité en </strong>
        <span className="highlight">psychologie</span>.
      </p>
      <div className="news-grid">
        {newsArticles.map((article) => (
          <article key={article.id} className="news-card">
            <img src={article.image} alt="" className="news-image" />
            <div className="news-content">
              <span className="news-category">{article.category}</span>
              <h3 className="news-title">{article.title}</h3>
            </div>
          </article>
        ))}
      </div>
      <a href="#" className="see-all-link">
        Voir tous les articles
      </a>
    </section>
  );
}

export default PsychologyNewsSection;
