/**
 * This code was generated by Builder.io.
 */
import React from "react";
import "./QuestionnaireSection.css";

function QuestionnaireSection() {
  return (
    <section className="questionnaire-section">
      <h2 className="section-title">Les questionnaires recommandés</h2>
      <p className="section-subtitle">
        Thérapies les plus demandées par les utilisateurs.
      </p>
      <div className="questionnaire-container">
        <div className="questionnaire-card">
          <div className="questionnaire-content">
            <h3 className="questionnaire-title">Test de bien-être</h3>
            <p className="questionnaire-description">
              évaluer votre bien-être mental grâce a nos test !
            </p>
            <a href="#" className="start-test-btn">
              Commencer le test
            </a>
          </div>
        </div>
        <div className="questionnaire-types">
          <div className="questionnaire-type">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/3d07634bb69f79f0034f2f78c00cf89a5c0df068b8ea2c60250825828771f0bb?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
              alt=""
              className="type-icon"
            />
            <span className="type-label">RAPIDE</span>
          </div>
          <div className="questionnaire-type">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/a5e1bb4feb166c0fb5d9958d98d144d76259ba75a1fb015d3ca362eb257261c2?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
              alt=""
              className="type-icon"
            />
            <span className="type-label">MOYEN</span>
          </div>
          <div className="questionnaire-type">
            <span className="type-label">POUSSE</span>
          </div>
        </div>
      </div>
      <a href="#" className="see-all-link">
        Voir Tous
      </a>
    </section>
  );
}

export default QuestionnaireSection;
