/**
 * This code was generated by Builder.io.
 */
import React from "react";
import "./SpecialistSearchSection.css";

function SpecialistSearchSection() {
  const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ#".split("");

  return (
    <section className="specialist-search-section">
      <h2 className="section-title">Chercher un spécialiste par nom</h2>
      <div className="alphabet-grid">
        {alphabet.map((letter) => (
          <a key={letter} href="#" className="alphabet-link">
            {letter}
          </a>
        ))}
      </div>
    </section>
  );
}

export default SpecialistSearchSection;
