/**
 * This code was generated by Builder.io.
 */
import React from "react";
import "./TopConsultationsSection.css";

function TopConsultationsSection() {
  const topQuestions = [
    {
      id: 1,
      question: "Mon fils de 14 ans a fait des attouchements sexuels",
      responses: 21,
    },
    {
      id: 2,
      question:
        "Quelle est la différence entre un psychologue et un psychiatre ?",
      responses: 13,
    },
    {
      id: 3,
      question:
        "Rêves et lieu : maison familiale ou maison d'enfance récurrente",
      responses: 11,
    },
    {
      id: 4,
      question:
        "Bonjour, que pensez vous d'un pere qui dort avec sa fille de 10 an…",
      responses: 22,
    },
    { id: 5, question: "Différence psychologie etpsychanalyse", responses: 12 },
    {
      id: 6,
      question: "Est-ce que mon professeur est attiré par moi ?",
      responses: 12,
    },
  ];

  return (
    <section className="top-consultations-section">
      <h2 className="section-title">Top Consultations</h2>
      <p className="section-description">
        <strong>Posez vos questions à un psy</strong> et faites le premier pas
        en regardant les <strong>questions</strong> d'autres utilisateurs.
      </p>
      <div className="questions-container">
        {topQuestions.map((item) => (
          <div key={item.id} className="question-item">
            <span className="question-number">{item.id}</span>
            <div className="question-content">
              <p className="question-text">{item.question}</p>
              <p className="response-count">{item.responses} réponses</p>
            </div>
          </div>
        ))}
      </div>
      <a href="#" className="see-all-link">
        Voir tous
      </a>
    </section>
  );
}

export default TopConsultationsSection;
