/**
 * This code was generated by Builder.io.
 */
import React from "react";
import PsychologistCard from "./PsychologistCard";

const psychologists = [
  {
    name: "Véronique Blanche",
    location: "Psy sur Quessoy",
    responses: 6558,
    positiveVotes: 4706,
    avatar:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/83348b5835bdc71dde636afb0204f9540314389872945967f515cfdf6042d04b?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae",
  },
  {
    name: "Inès Avot",
    location: "Psy sur Ouve-Wirquin",
    responses: 6354,
    positiveVotes: 3554,
    avatar:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/421024299cd1b5f5d11645ee086b2d2b1486b90892063e015b0ba9b6d1ca2f65?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae",
  },
  {
    name: "Nathalie Follmann",
    location: "Psy sur Clichy",
    responses: 5432,
    positiveVotes: 32231,
    avatar:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/9cb22f1c360abc435c78deaec2819189ad5383a6b4d29f27ce3520db4494134b?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae",
  },
  {
    name: "Silvia Podani",
    location: "Psy sur Issy-les-Moulineaux",
    responses: 4568,
    positiveVotes: 12518,
    avatar:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/211c808cd81b7a65ba018f7adf45924c07259d509245fd0ca649713e28ffe30f?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae",
  },
  {
    name: "Michel Le Baut",
    location: "Psy sur Marseille",
    responses: 4414,
    positiveVotes: 22491,
    avatar:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/37f52a10cea4f3f626b24f8858f21ae77a54a3f0fd2761c9905431ca3a40e74e?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae",
  },
  {
    name: "Christophe Nieaux",
    location: "Psy sur Melun",
    responses: 3661,
    positiveVotes: 3868,
    avatar:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/7f59df673084d3c8ef6a604388540a058c322c0517b160a67935a67da2350055?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae",
  },
];

const ActivePsychologists = () => {
  return (
    <section className="active-psychologists">
      <h2 className="section-title">Psy les plus actifs</h2>
      <div className="psychologist-grid">
        {psychologists.map((psychologist, index) => (
          <PsychologistCard key={index} {...psychologist} />
        ))}
      </div>
    </section>
  );
};

export default ActivePsychologists;
