/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Footer = () => {
  return (
    <footer className="main-footer">
      <div className="footer-content">
        <div className="footer-columns">
          <div className="footer-column">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/0f9bc6aae80fcabc97dba7a9e4645b4fbf0e9097b386769bf4abce07c6455680?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
              className="footer-logo"
              alt="Logo Good Mental"
            />
            <nav className="footer-nav">
              <a href="#" className="footer-link">
                À propos
              </a>
              <a href="#" className="footer-link">
                Mentions légales
              </a>
              <a href="#" className="footer-link">
                Protection des données
              </a>
              <a href="#" className="footer-link">
                Politique publicitaire
              </a>
              <a href="#" className="footer-link">
                Politique de cookies
              </a>
              <a href="#" className="footer-link">
                Comment nous vous montrons les résultats
              </a>
              <a href="#" className="footer-link">
                Opinions
              </a>
            </nav>
          </div>
          <div className="footer-column">
            <nav className="footer-nav">
              <a href="#" className="footer-link">
                Plan Premium
              </a>
              <a href="#" className="footer-link">
                Ajoutez votre cabinet
              </a>
              <a href="#" className="footer-link">
                Connexion professionnels
              </a>
              <a href="#" className="footer-link">
                Annoncez-vous
              </a>
              <a href="#" className="footer-link">
                Avez-vous besoin d'aide ?
              </a>
            </nav>
          </div>
          <div className="footer-column">
            <h3 className="footer-heading">Derniers cabinets</h3>
            <nav className="footer-nav">
              <a href="#" className="footer-link">
                Veronique Macheix
              </a>
              <a href="#" className="footer-link">
                Nadra Rouzeik
              </a>
              <a href="#" className="footer-link">
                Gilles de la Londe Aurore
              </a>
              <a href="#" className="footer-link">
                Julia Radoszycki
              </a>
              <a href="#" className="footer-link">
                Ludivine Noirault
              </a>
            </nav>
            <h3 className="footer-heading">Top villes</h3>
            <nav className="footer-nav">
              <a href="#" className="footer-link">
                Psychologues Paris
              </a>
              <a href="#" className="footer-link">
                Psychologues Gironde
              </a>
              <a href="#" className="footer-link">
                Psychologues Bouches-du-Rhône
              </a>
              <a href="#" className="footer-link">
                Psychologues Rhône
              </a>
              <a href="#" className="footer-link">
                Psychologues Haute-Garonne
              </a>
              <a href="#" className="footer-link">
                Villes
              </a>
            </nav>
            <h3 className="footer-heading">Dernières recherches</h3>
            <nav className="footer-nav">
              <a href="#" className="footer-link">
                Psychothérapie
              </a>
              <a href="#" className="footer-link">
                Psychologie enfant
              </a>
              <a href="#" className="footer-link">
                Psychanalyse
              </a>
              <a href="#" className="footer-link">
                Thérapie de couple
              </a>
            </nav>
          </div>
        </div>
        <div className="footer-social">
          <p>Suivez-nous:</p>
          <a href="#" aria-label="Facebook">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/efccb5338f99556e5fb7321db537802f2a4b17e40a0f48d9f81ae3525dac6e5f?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
              className="social-icon"
              alt="Facebook"
            />
          </a>
          <a href="#" aria-label="Twitter">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/5c1327c7253ec8130b7eb603ef3d341d69c50b5ec3b3160bad575e7985000f49?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
              className="social-icon"
              alt="Twitter"
            />
          </a>
        </div>
      </div>
      <div className="footer-copyright">
        © 2005 - 2024 GoodMental.fr Tous droits réservés. Mise à jour: October
        2024
      </div>
    </footer>
  );
};

export default Footer;
