/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Navigation = () => {
  return (
    <nav className="main-navigation">
      <div className="nav-group">
        <a href="#" className="nav-link">
          Psychologues en ligne
        </a>
        <a href="#" className="nav-link">
          Cabinets
        </a>
      </div>
      <div className="nav-group">
        <a href="#" className="nav-link">
          Questions
        </a>
        <div className="nav-item">
          <a href="#" className="nav-link">
            Ateliers et cours
          </a>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/f7b5e8aa06b34798ddbe8d6e1b97146bbc2a1d83fbe0b8db8691f3f431fa0524?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
            className="nav-icon"
            alt=""
          />
        </div>
        <div className="nav-item">
          <a href="#" className="nav-link">
            Bien-être émotionnel
          </a>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/a3bcdf2c4974ff64912d5bc2b4ed98d7d75bf1784f4727d82e672e9dfdaafebd?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
            className="nav-icon"
            alt=""
          />
        </div>
        <div className="nav-item">
          <a href="#" className="nav-link">
            Inscrivez-vous
          </a>
          <span className="vertical-divider"></span>
          <a href="#" className="nav-link">
            Entrez
          </a>
        </div>
        <div className="nav-item professional-space">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/d4282109d1bfcf202ad1292d3ea41b59cb30ecb943f813c51334b28f39afbe95?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
            className="nav-icon"
            alt=""
          />
          <a href="#" className="nav-link">
            Espace professionnel
          </a>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/211eea900889d5391df067315978318ed7c214306ca0dd95b9301fd544c95cfe?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
            className="nav-icon"
            alt=""
          />
        </div>
      </div>
    </nav>
  );
};

export default Navigation;
