/**
 * This code was generated by Builder.io.
 */
import React from "react";

const PsychologistCard = ({
  name,
  location,
  responses,
  positiveVotes,
  avatar,
}) => {
  return (
    <div className="psychologist-card">
      <div className="psychologist-info">
        <img
          loading="lazy"
          src={avatar}
          className="psychologist-avatar"
          alt={`Avatar de ${name}`}
        />
        <div className="psychologist-details">
          <h3 className="psychologist-name">{name}</h3>
          <p className="psychologist-location">{location}</p>
          <div className="psychologist-stats">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/8e549f1007862756501d58fb5e22d70fbae61aa0c060284226f51aa70fa2c8ea?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
              className="stat-icon"
              alt=""
            />
            <p>
              {responses} <span className="stat-label">réponses</span>
            </p>
          </div>
        </div>
      </div>
      <div className="psychologist-votes">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/981650942c017ab3c84f3be3208c59b6a095f3aece499cd330494121a0e452c5?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
          className="vote-icon"
          alt=""
        />
        <p>
          {positiveVotes} <span className="stat-label">Votes positifs</span>
        </p>
      </div>
    </div>
  );
};

export default PsychologistCard;
