/**
 * This code was generated by Builder.io.
 */
import React from "react";
import QuestionCard from "./QuestionCard";

const questions = [
  {
    date: "5 OCT. 2024",
    title:
      "Deçue et en colere contre ma therapeute. Bonjour, j'ai entrepris depuis environ 2 ans une...",
    content:
      "Bonjour, j'ai entrepris depuis environ 2 ans une thérapie pour traiter des problèmes de confiance en moi, estime, rumination et peur du lendemain. Cela s'est assez",
    continuation: "bien passé dans l'ensemble. J'...",
    bestAnswer: {
      date: "AUJOURD'HUI, 7 OCT. 2024",
      content:
        "Bonjour Manelle, il arrive qu'un.e praticien.ne réfère ses patient.es à des collègues qui ont des spécialités complémentaires pour traiter une problématique spécifique, comme par exemple l'EMDR dans l...",
      author: {
        name: "Sandrine Bowen",
        location: "Psy sur Aire-sur-l'Adour",
      },
    },
  },
  {
    date: "1 OCT. 2024",
    title:
      "Il ne sait plus s'il m'aime …. Bonjour , En couple depuis 3 ans officiellement , après l'...",
    content:
      "Bonjour , En couple depuis 3 ans officiellement , après l'avoir été 1 an illégitimement ( année incluant 2 ruptures par peur de perdre sa famille) , nous voici dans",
    continuation: "l'impasse . Pourtant je n'ai jama...",
    bestAnswer: {
      date: "HIER, 6 OCT. 2024",
      content:
        "Bonjour Julia, Il est en effet possible que votre conjoint fasse une dépression, il faudrait qu'il soit vu par un médecin. Bien que la démarche doive venir de lui, vous pouvez tenter de l'inciter à e...",
      author: {
        name: "Agnes Favard",
        location: "Psy sur Gardanne",
      },
    },
  },
  {
    date: "1 OCT. 2024",
    title:
      "Que pensez vous de la sophro analyse ?. J'ai consulté une personne débutante en sophro ana...",
    content:
      "J'ai consulté une personne débutante en sophro analyse et mes troubles anxieux se sont décuplés, c'est terrible j'entends la voix de cette femme très souvent. J'ai",
    continuation: "arrêté et elle m'a harcelé ainsi que...",
    bestAnswer: {
      date: "HIER, 6 OCT. 2024",
      content:
        "Bonjour Michelle, Etant moi-même sophrologue certifiée RNCP et diplômée en psychothérapie intégrative (plus de 11 années de formation), je peux vous répondre. La sophrologie et la sophro-analyse son...",
      author: {
        name: "Caroline Gormand",
        location: "Psy sur Clermont-l'Hérault",
      },
    },
  },
];

const QuestionSection = () => {
  return (
    <section className="question-section">
      <h2 className="section-title">Dernières questions</h2>
      {questions.map((question, index) => (
        <QuestionCard key={index} {...question} />
      ))}
      <a href="#" className="view-all-link">
        Voir toutes les questions
      </a>
    </section>
  );
};

export default QuestionSection;
