/**
 * This code was generated by Builder.io.
 */
import React from "react";

const QuestionCard = ({ date, title, content, continuation, bestAnswer }) => {
  return (
    <article className="question-card">
      <time className="question-date">{date}</time>
      <h3 className="question-title">{title}</h3>
      <p className="question-content">{content}</p>
      <div className="question-continuation">
        <p>{continuation}</p>
        <a href="#" className="view-question-link">
          Voir question
        </a>
      </div>
      {bestAnswer && (
        <div className="best-answer">
          <div className="answer-header">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/0217173ea9c27788a3ba280e1aabde656d79d9231fadc342ad6bb6f1f65dc981?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
              className="best-answer-icon"
              alt=""
            />
            <span className="best-answer-label">Meilleure réponse</span>
            <time className="answer-date">{bestAnswer.date}</time>
          </div>
          <p className="answer-content">{bestAnswer.content}</p>
          <div className="answer-author">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/35ffc22e8ac8eeaf55a80f691b0ec684e5d38e4e59ae87694843f87a54cec481?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
              className="author-avatar"
              alt=""
            />
            <div className="author-info">
              <p className="author-name">{bestAnswer.author.name}</p>
              <p className="author-location">{bestAnswer.author.location}</p>
              <a href="#" className="contact-button">
                Contacter
              </a>
            </div>
          </div>
        </div>
      )}
      <a href="#" className="view-all-answers-link">
        Voir toutes les réponses
      </a>
    </article>
  );
};

export default QuestionCard;
