/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const SearchSection = () => {
  return (
    <section className="search-section">
      <h2 className="section-title">Cherchez parmi les questions déjà existantes</h2>
      <p className="section-description">
        Trouver des réponses parmi les 14,450 questions posées sur Good Mental
      </p>
      <form className="search-form">
        <label htmlFor="search-input" className="visually-hidden">
          Cherchez parmi les questions déjà existantes
        </label>
        <div className="search-input-wrapper">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/ed56cd1ef4a608db9072f8f0dda55c0e7284e3e48bc89f05ff2c7fa1f5adbb12?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
            className="search-icon"
            alt=""
          />
          <input
            type="text"
            id="search-input"
            className="search-input"
            placeholder="Cherchez parmi les questions déjà existantes"
            aria-label="Cherchez parmi les questions déjà existantes"
          />
        </div>
        <button type="submit" className="search-button">Trouver</button>
      </form>
    </section>
  );
};

export default SearchSection;
