/**
 * This code was generated by Builder.io.
 */
import "./CSS4.css"
import React from "react";
import QuestionSection from "./QuestionSection";
import TopConsultations from "./TopConsultations";
import ActivePsychologists from "./ActivePsychologists";
import SearchSection from "./SearchSection";
import Footer from "./Footer";
import NavBar from "../../NavBar";

const UserquatreInterface = () => {
  return (
    <div className="main-layout">
      <NavBar />
      <main className="main-content">
        <div className="background-light">
          <div className="content-wrapper">
            <nav className="breadcrumb" aria-label="Breadcrumb">
              <a href="#" className="breadcrumb-link">
                FAQ
              </a>
            </nav>
            <QuestionSection />
            <TopConsultations />
            <ActivePsychologists />
            <SearchSection />
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default UserquatreInterface;
