/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Button = ({ children, type }) => {
  return (
    <button type={type} className="button">
      {children}
      <style jsx>{`
        .button {
          border-radius: 4px;
          background-color: #439a97;
          color: #fff;
          font-weight: 600;
          white-space: nowrap;
          text-align: center;
          line-height: 1;
          padding: 18px 70px;
          width: 100%;
          border: none;
          cursor: pointer;
        }
      `}</style>
    </button>
  );
};

export default Button;
