/**
 * This code was generated by Builder.io.
 */
import React from "react";

const CheckboxField = ({ label, id }) => {
  return (
    <div className="checkbox-field">
      <input type="checkbox" id={id} className="checkbox-field__input" />
      <label htmlFor={id} className="checkbox-field__label">
        {label}
      </label>
      <style jsx>{`
        .checkbox-field {
          display: flex;
          align-items: center;
          margin-bottom: 20px;
        }
        .checkbox-field__input {
          margin-right: 10px;
        }
        .checkbox-field__label {
          color: #243953;
          font-weight: 400;
          line-height: 1.4;
        }
      `}</style>
    </div>
  );
};

export default CheckboxField;
