/**
 * This code was generated by Builder.io.
 */
import React from "react";

const InputField = ({ label, type, id }) => {
  return (
    <div className="input-field">
      <label htmlFor={id} className="input-field__label">
        {label}
      </label>
      <input type={type} id={id} className="input-field__input" />
      <style jsx>{`
        .input-field {
          width: 100%;
          margin-bottom: 23px;
        }
        .input-field__label {
          color: #243953;
          font-weight: 600;
          line-height: 1.4;
          display: block;
          margin-bottom: 8px;
        }
        .input-field__input {
          border-radius: 5px;
          background-color: #fff;
          width: 100%;
          height: 45px;
          border: 1px solid #d0d6e1;
          padding: 0 10px;
        }
      `}</style>
    </div>
  );
};

export default InputField;
