/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Link = ({ href, children, className }) => {
  return (
    <a href={href} className={`link ${className}`}>
      {children}
      <style jsx>{`
        .link {
          color: #439a97;
          font-weight: 600;
          text-decoration: none;
        }
      `}</style>
    </a>
  );
};

export default Link;
