/**
 * This code was generated by Builder.io.
 */
import React from "react";
import InputField from "./InputField";
import CheckboxField from "./CheckboxField";
import Button from "./Button";
import Link from "./Link";

const LoginForm = () => {
  return (
    <form className="login-form">
      <h2 className="login-form__title">
        Vous êtes un utilisateurs déjà inscrit ?
      </h2>
      <InputField label="Identifiant" type="text" id="username" />
      <InputField label="Mot de passe" type="password" id="password" />
      <CheckboxField label="Rester connecté" id="stay-connected" />
      <Button type="submit">Connexion</Button>
      <Link href="#" className="login-form__forgot-password">
        Mot de passe oublié ?
      </Link>
      <div className="login-form__signup">
        <span>Toujours pas inscrit?</span>
        <Link href="#">Créer un compte gratuit.</Link>
      </div>
      <style jsx>{`
        .login-form {
          border-radius: 0 16px 16px 0;
          background-color: #fff;
          box-shadow: 8px 4px 15px #dde2e9;
          display: flex;
          max-width: 462px;
          flex-direction: column;
          align-items: flex-start;
          padding: 57px 32px 93px;
          font-family: Hind, sans-serif;
        }
        .login-form__title {
          color: #243953;
          font-size: 18px;
          font-weight: 700;
          letter-spacing: -0.19px;
          margin-bottom: 45px;
        }
        .login-form__forgot-password {
          color: #439a97;
          font-weight: 600;
          line-height: 1.4;
          text-align: center;
          align-self: center;
          margin-top: 46px;
        }
        .login-form__signup {
          display: flex;
          margin-top: 34px;
          gap: 5px;
          line-height: 1;
        }
        .login-form__signup span {
          color: #243952;
          font-weight: 400;
        }
      `}</style>
    </form>
  );
};

export default LoginForm;
