/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ArticleCard = ({ image, category, title, author, date }) => {
  return (
    <article className="article-card">
      <img src={image} alt="" className="article-image" />
      <div className="article-content">
        <span className="article-category">{category}</span>
        <h3 className="article-title">{title}</h3>
        <div className="article-meta">
          <span>
            Par <strong>{author}</strong> · {date}
          </span>
        </div>
      </div>
    </article>
  );
};

export default ArticleCard;
