/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Breadcrumb = () => {
  return (
    <nav className="breadcrumb" aria-label="Breadcrumb">
      <ol>
        <li>
          <a href="#">Nos questionnaires</a>
        </li>
        <li aria-current="page">Articles</li>
      </ol>
    </nav>
  );
};

export default Breadcrumb;
