/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Footer = () => {
  return (
    <footer className="main-footer">
      <div className="footer-content">
        <div className="footer-columns">
          <div className="footer-column">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/0f9bc6aae80fcabc97dba7a9e4645b4fbf0e9097b386769bf4abce07c6455680?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
              alt="Logo"
              className="footer-logo"
            />
            <nav className="footer-nav">
              <a href="#" className="footer-link">
                À propos
              </a>
              <a href="#" className="footer-link">
                Mentions légales
              </a>
              <a href="#" className="footer-link">
                Protection des données
              </a>
              <a href="#" className="footer-link">
                Politique publicitaire
              </a>
              <a href="#" className="footer-link">
                Politique de cookies
              </a>
              <a href="#" className="footer-link">
                Comment nous vous montrons les résultats
              </a>
              <a href="#" className="footer-link">
                Opinions
              </a>
            </nav>
            <nav className="footer-nav">
              <a href="#" className="footer-link">
                Plan Premium
              </a>
              <a href="#" className="footer-link">
                Ajoutez votre cabinet
              </a>
              <a href="#" className="footer-link">
                Connexion professionnels
              </a>
              <a href="#" className="footer-link">
                Annoncez-vous
              </a>
              <a href="#" className="footer-link">
                Avez-vous besoin d'aide ?
              </a>
            </nav>
          </div>
          <div className="footer-column">
            <h3 className="footer-heading">Derniers cabinets</h3>
            <ul className="footer-list">
              <li>
                <a href="#" className="footer-link">
                  Veronique Macheix
                </a>
              </li>
              <li>
                <a href="#" className="footer-link">
                  Nadra Rouzeik
                </a>
              </li>
              <li>
                <a href="#" className="footer-link">
                  Gilles de la Londe Aurore
                </a>
              </li>
              <li>
                <a href="#" className="footer-link">
                  Julia Radoszycki
                </a>
              </li>
              <li>
                <a href="#" className="footer-link">
                  Ludivine Noirault
                </a>
              </li>
            </ul>
            <h3 className="footer-heading">Top villes</h3>
            <ul className="footer-list">
              <li>
                <a href="#" className="footer-link">
                  Psychologues Paris
                </a>
              </li>
              <li>
                <a href="#" className="footer-link">
                  Psychologues Gironde
                </a>
              </li>
              <li>
                <a href="#" className="footer-link">
                  Psychologues Bouches-du-Rhône
                </a>
              </li>
              <li>
                <a href="#" className="footer-link">
                  Psychologues Rhône
                </a>
              </li>
              <li>
                <a href="#" className="footer-link">
                  Psychologues Haute-Garonne
                </a>
              </li>
            </ul>
            <a href="#" className="footer-link">
              Villes
            </a>
            <h3 className="footer-heading">Dernières recherches</h3>
            <ul className="footer-list">
              <li>
                <a href="#" className="footer-link">
                  Psychothérapie
                </a>
              </li>
              <li>
                <a href="#" className="footer-link">
                  Psychologie enfant
                </a>
              </li>
              <li>
                <a href="#" className="footer-link">
                  Psychanalyse
                </a>
              </li>
              <li>
                <a href="#" className="footer-link">
                  Thérapie de couple
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div className="footer-social">
          <span>Suivez-nous:</span>
          <a href="#" aria-label="Facebook">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/be03ef8668eded32cbdc83b6ff9a5f62b1ed7b38da69940842996ce91c747677?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
              alt=""
              className="social-icon"
            />
          </a>
          <a href="#" aria-label="Twitter">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/b04e5d9348ef041b5b5fad9144f47190876420c173f2a33ceb190312f01aebc8?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
              alt=""
              className="social-icon"
            />
          </a>
        </div>
      </div>
      <div className="footer-copyright">
        © 2005 - 2024 GoodMental.fr Tous droits réservés. Mise à jour: October
        2024
      </div>
    </footer>
  );
};

export default Footer;
