/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Header = () => {
  return (
    <header className="main-header">
      <div className="header-content">
        <div className="logo-nav-wrapper">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/4f6b5e5caa5d3ab2c7a7937f7acf0f65f24b80e96ec53586a62c3ce9be19db9b?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
            alt="Logo"
            className="logo"
          />
          <nav className="main-nav">
            <a href="#" className="nav-link">
              Nos questionnaires
            </a>
            <a href="#" className="nav-link">
              Chat
            </a>
            <a href="#" className="nav-link">
              Dashboard
            </a>
            <a href="#" className="nav-link">
              Notification
            </a>
            <a href="#" className="nav-link">
              FAQ
            </a>
          </nav>
        </div>
        <div className="about-wrapper">
          <a href="#" className="about-link">
            A propos
          </a>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/8a7fd86dd33225b40f03266984117ac5ec74740425b98eea7da29a92ed188b63?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
            alt=""
            className="about-icon"
          />
        </div>
        <div className="pro-space-wrapper">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/cd691faaa058c0d8eb37075912f6e4efea96ea389ebe05037a10872a57cb4974?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
            alt=""
            className="pro-icon"
          />
          <a href="#" className="pro-link">
            Espace professionnel
          </a>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/9e349d3d3942c609705a9d6dca8f4130583beca71a46d17921e2bca3a1965828?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
            alt=""
            className="arrow-icon"
          />
        </div>
      </div>
    </header>
  );
};

export default Header;
