/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Pagination = ({ currentPage, totalPages }) => {
  const pageNumbers = [];
  for (let i = 1; i <= totalPages; i++) {
    pageNumbers.push(i);
  }

  return (
    <nav className="pagination" aria-label="Pagination">
      <button
        className="pagination-prev"
        aria-label="Page précédente"
        disabled={currentPage === 1}
      >
        &lt;
      </button>
      {pageNumbers.map((number) => (
        <button
          key={number}
          className={`pagination-number ${
            currentPage === number ? "active" : ""
          }`}
          aria-label={`Page ${number}`}
          aria-current={currentPage === number ? "page" : null}
        >
          {number}
        </button>
      ))}
      <button
        className="pagination-next"
        aria-label="Page suivante"
        disabled={currentPage === totalPages}
      >
        &gt;
      </button>
    </nav>
  );
};

export default Pagination;
