/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ProfessionalArticleCard = ({ image, category, title, author, date }) => {
  return (
    <article className="pro-article-card">
      <img src={image} alt="" className="pro-article-image" />
      <div className="pro-article-content">
        <span className="pro-article-category">{category}</span>
        <h3 className="pro-article-title">{title}</h3>
        <div className="pro-article-meta">
          <span>Par</span>
          <div>
            <span className="pro-article-author">{author}</span>
            <span className="pro-article-date">· {date}</span>
          </div>
        </div>
      </div>
    </article>
  );
};

export default ProfessionalArticleCard;
