/**
 * This code was generated by Builder.io.
 */
import React from "react";

const CallToAction = () => {
  return (
    <section className="cta-section">
      <div className="cta-content">
        <h2 className="cta-title">Commencez dès maintenant</h2>
        <p className="cta-description">
          Rejoignez Psychologue.net{" "}
          <strong>pour développer votre carrière professionnelle.</strong>
          <br />
          Améliorez vos leads, gérez vos rendez-vous et gagnez plus de
          réputation.
        </p>
        <a href="#signup" className="cta-button">
          Créez votre compte gratuit
        </a>
      </div>
    </section>
  );
};

export default CallToAction;
