/**
 * This code was generated by Builder.io.
 */
import React from "react";

const features = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/0ea82f6d164c07f34f13b22e885f553c0ee2b60fceba7b8c8373063abd90569c?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae",
    text: "Mettez en avant votre profil et gagnez en visibilité",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/a4a9bfa3a0e6e07ac59763d27bb7990675e46b4cd52309939d47ba3879aa186a?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae",
    text: "Faites de la Thérapie en ligne",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/6abee3e78c138f986aaf97070e8b7dceb63e80aeac3a649d366cad56f309287c?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae",
    text: "Gérez vos demandes des rdv",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/dd3f94a4fc18f35990b2bcc5062c0451f99ae8780163abb72f28ab5e33bdeb8e?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae",
    text: "Suivi de l'état de vos patients",
  },
];

const FeatureList = () => {
  return (
    <ul className="feature-list">
      {features.map((feature, index) => (
        <li key={index} className="feature-item">
          <img src={feature.icon} alt="" className="feature-icon" />
          <p className="feature-text">{feature.text}</p>
        </li>
      ))}
    </ul>
  );
};

export default FeatureList;
