/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Footer = () => {
  return (
    <footer className="main-footer">
      <div className="footer-content">
        <div className="footer-columns">
          <div className="footer-column">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/0f9bc6aae80fcabc97dba7a9e4645b4fbf0e9097b386769bf4abce07c6455680?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
              alt="Company Logo"
              className="footer-logo"
            />
            <nav className="footer-nav">
              <ul>
                <li>
                  <a href="#about">À propos</a>
                </li>
                <li>
                  <a href="#legal">Mentions légales</a>
                </li>
                <li>
                  <a href="#privacy">Protection des données</a>
                </li>
                <li>
                  <a href="#advertising">Politique publicitaire</a>
                </li>
                <li>
                  <a href="#cookies">Politique de cookies</a>
                </li>
                <li>
                  <a href="#results">
                    Comment nous vous montrons les résultats
                  </a>
                </li>
                <li>
                  <a href="#opinions">Opinions</a>
                </li>
              </ul>
            </nav>
            <nav className="footer-nav">
              <ul>
                <li>
                  <a href="#premium">Plan Premium</a>
                </li>
                <li>
                  <a href="#add-cabinet">Ajoutez votre cabinet</a>
                </li>
                <li>
                  <a href="#pro-login">Connexion professionnels</a>
                </li>
                <li>
                  <a href="#advertise">Annoncez-vous</a>
                </li>
                <li>
                  <a href="#help">Avez-vous besoin d'aide ?</a>
                </li>
              </ul>
            </nav>
          </div>
          <div className="footer-column">
            <h3>Derniers cabinets</h3>
            <ul className="recent-cabinets">
              <li>Veronique Macheix</li>
              <li>Nadra Rouzeik</li>
              <li>Gilles de la Londe Aurore</li>
              <li>Julia Radoszycki</li>
              <li>Ludivine Noirault</li>
            </ul>
            <h3>Top villes</h3>
            <ul className="top-cities">
              <li>
                <a href="#paris">Psychologues Paris</a>
              </li>
              <li>
                <a href="#gironde">Psychologues Gironde</a>
              </li>
              <li>
                <a href="#bouches-du-rhone">Psychologues Bouches-du-Rhône</a>
              </li>
              <li>
                <a href="#rhone">Psychologues Rhône</a>
              </li>
              <li>
                <a href="#haute-garonne">Psychologues Haute-Garonne</a>
              </li>
            </ul>
            <h3>Dernières recherches</h3>
            <ul className="recent-searches">
              <li>Psychothérapie</li>
              <li>Psychologie enfant</li>
              <li>Psychanalyse</li>
              <li>Thérapie de couple</li>
            </ul>
          </div>
        </div>
        <div className="social-links">
          <p>Suivez-nous:</p>
          <a href="#facebook" aria-label="Facebook">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/364bebe39969cf906322acc7e6006259a1841c5e23f32ed163a53c12e1e43d39?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
              alt=""
              className="social-icon"
            />
          </a>
          <a href="#twitter" aria-label="Twitter">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/f5fc345e394c66151edbbc4d6d03ea0c40123a0c24b94df96d62e1083955a600?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
              alt=""
              className="social-icon"
            />
          </a>
        </div>
      </div>
      <div className="copyright">
        © 2005 - 2024 GoodMental.fr Tous droits réservés. Mise à jour: October
        2024
      </div>
    </footer>
  );
};

export default Footer;
