/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FeatureList from "./FeatureList";

const HeroSection = () => {
  return (
    <section className="hero-section">
      <div className="hero-content">
        <h1 className="hero-title">
          Boostez votre cabinet <br /> avec{" "}
          <span className="highlight">GoodMental.fr</span>
        </h1>
        <p className="hero-subtitle">
          <span className="bold">Rejoignez la </span>
          communauté la plus exclusive de
        </p>
        <p className="hero-description">
          <span className="bold">professionnels de la psychologie </span>
          <span className="highlight">émotionnel.</span>
          <br />
          et du bien-être
        </p>
        <FeatureList />
        <a href="#signup" className="cta-button">
          Inscrivez-vous gratuitement
        </a>
      </div>
    </section>
  );
};

export default HeroSection;
