/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Navigation = () => {
  return (
    <nav className="main-navigation">
      <ul className="nav-list">
        <li>
          <a href="#questionnaires">Nos questionnaires</a>
        </li>
        <li>
          <a href="#chat">Chat</a>
        </li>
        <li>
          <a href="#dashboard">Dashboard</a>
        </li>
        <li>
          <a href="#notification">Notification</a>
        </li>
        <li>
          <a href="#faq">FAQ</a>
        </li>
      </ul>
      <div className="nav-about">
        <a href="#about">A propos</a>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/b3d716a79133ba276a1b0f7f4fc2925ddc5f9b620dfd5698cd96045a0482a0aa?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
          alt=""
          className="nav-icon"
        />
      </div>
      <div className="pro-space">
        <a href="#pro-space" className="pro-link">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/1a80e0e0c423646e7627d12cc858ca543ac4e4682635cc92c91f040ee8d7f75b?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
            alt=""
            className="pro-icon"
          />
          <span>Espace professionnel</span>
        </a>
        <a href="#pro-space-alt" className="pro-link-alt">
          <span>Espace professionnel</span>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/1239815d1350c3a934b0d33fbdac0bd08f2c1beee67d14b87586ac3598c2289f?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
            alt=""
            className="pro-icon-alt"
          />
        </a>
      </div>
    </nav>
  );
};

export default Navigation;
