/**
 * This code was generated by Builder.io.
 */
import React from "react";

const SignupForm = () => {
  return (
    <section className="signup-section">
      <form className="signup-form">
        <h2 className="form-title">
          Créez votre <span className="highlight">compte gratuit</span>
        </h2>
        <fieldset>
          <legend>Je suis un :</legend>
          <div className="radio-group">
            <label className="radio-label">
              <input type="radio" name="accountType" value="independent" />
              <span className="radio-text">Indépendant</span>
            </label>
            <label className="radio-label">
              <input type="radio" name="accountType" value="cabinet" />
              <span className="radio-text">Cabinet</span>
            </label>
          </div>
        </fieldset>
        <label htmlFor="fullName">Nom et Prénom du professionnel</label>
        <input
          type="text"
          id="fullName"
          name="fullName"
          placeholder="Tel qu'il apparaît dans le Registre des Psychologues"
          required
        />
        <label htmlFor="registrationNumber">
          Nº ADELI ou SIRET de votre cabinet
        </label>
        <input
          type="text"
          id="registrationNumber"
          name="registrationNumber"
          placeholder="Tel qu'il apparaît dans le Registre des Psychologues"
          required
        />
        <label htmlFor="phone">Téléphone portable</label>
        <div className="phone-input">
          <span className="country-code">+33</span>
          <input
            type="tel"
            id="phone"
            name="phone"
            placeholder="Téléphone portable"
            required
          />
        </div>
        <label htmlFor="location">Localité de votre centre</label>
        <input
          type="text"
          id="location"
          name="location"
          placeholder="Localité de votre centre"
          required
        />
        <label htmlFor="email">E-mail</label>
        <input
          type="email"
          id="email"
          name="email"
          placeholder="votreemail@domaine.com"
          required
        />
        <label htmlFor="password">Tapez votre mot de passe</label>
        <input
          type="password"
          id="password"
          name="password"
          placeholder="Tapez votre mot de passe"
          required
        />
        <label htmlFor="referenceCode">
          Code de référence interne (Optionnel)
        </label>
        <input
          type="text"
          id="referenceCode"
          name="referenceCode"
          placeholder="Si vous avez un code de référence, écrivez-le ici."
        />
        <div className="checkbox-group">
          <label className="checkbox-label">
            <input type="checkbox" name="termsAccepted" required />
            <span>
              J'ai lu et j'accepte les <a href="#terms">Mentions légales</a> et
              la <a href="#privacy">Politique de protection des données</a>.
            </span>
          </label>
        </div>
        <div className="checkbox-group">
          <label className="checkbox-label">
            <input type="checkbox" name="marketingConsent" />
            <span>
              J'accepte de recevoir des informations commerciales de la part de
              Psychologue.net et je comprends que je peux me désabonner à tout
              moment.
            </span>
          </label>
        </div>
        <button type="submit" className="submit-button">
          Inscrivez-vous gratuitement
        </button>
      </form>
    </section>
  );
};

export default SignupForm;
