/**
 * This code was generated by Builder.io.
 */
import React from "react";

const testimonials = [
  {
    quote:
      "Grâce à une collaboration de plus de cinq ans avec le portail GoodMorning.fr j'ai pu faire reconnaître mon professionnalisme tout en me faisant connaître auprès de personnes intéressées par une aide psychologique.",
    author: "Dr. Leonardo Mometti",
    title: "médecin psychothérapeute",
    avatar:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/a1190a33acc26a9aa14ee70e2bb4880565dcf206768b7462af4e008985779658?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae",
  },
  {
    quote:
      "Je me sens chanceux de faire partie de GoodMorning.fr, cette dernière année les résultats ont été positifs grâce à une meilleure visibilité en ligne.",
    author: "Dr. Mirko Di Giulio",
    title: "médecin psychothérapeute",
    avatar:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/ded4c3f41a70e2ff1c887626e2cf40730839396d6dd31c42f11b7ed3a74f3d43?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae",
  },
];

const Testimonials = () => {
  return (
    <section className="testimonials-section">
      <h2 className="section-title">OPINIONS</h2>
      <h3 className="testimonials-title">Ce qu'en disent nos clients</h3>
      <div className="testimonials-container">
        {testimonials.map((testimonial, index) => (
          <article key={index} className="testimonial-card">
            <img
              src={
                index === 0
                  ? "https://cdn.builder.io/api/v1/image/assets/TEMP/22ec8b1b7dfa96c60ae952a4392a82be103a7995d9765d01fdb59c3b0c11589b?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
                  : "https://cdn.builder.io/api/v1/image/assets/TEMP/2a00426eb24a0bf0250a65fe4f873da1ca3468fa1b7473000b819267e1521b4d?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
              }
              alt=""
              className="testimonial-icon"
            />
            <blockquote className="testimonial-quote">
              {testimonial.quote}
            </blockquote>
            <footer className="testimonial-footer">
              <img
                src={testimonial.avatar}
                alt={testimonial.author}
                className="testimonial-avatar"
              />
              <div className="testimonial-author">
                <cite className="author-name">{testimonial.author}</cite>
                <p className="author-title">{testimonial.title}</p>
              </div>
            </footer>
          </article>
        ))}
      </div>
    </section>
  );
};

export default Testimonials;
