/**
 * This code was generated by Builder.io.
 */
import React from "react";

const FindTherapist = () => {
  return (
    <section className="find-therapist">
      <div className="content-wrapper">
        <h2 className="section-title">Trouvez votre psy</h2>
        <p className="section-description">
          Trouvez ici l'aide des{" "}
          <strong>
            meilleurs psychologues, psychothérapeutes et psychopraticiens
          </strong>{" "}
          et suivez une <strong>thérapie en ligne ou en personne</strong>
        </p>
        <div className="search-container">
          <div className="search-options">
            <div className="therapy-type">
              <button className="therapy-button online">
                <img
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/3cd212665cd8696129dbdb873a9c100ff94cb2644ffff300b6cab1eb490e2121?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
                  alt=""
                  className="therapy-icon"
                />
                <span>Thérapie en ligne</span>
              </button>
              <button className="therapy-button in-person">
                <img
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/591e8f458c5dfb1e32dc8f8cca3cb88418030f810edeebbe273e4cf69890cb0d?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
                  alt=""
                  className="therapy-icon"
                />
                <span>Thérapie présentiel</span>
              </button>
            </div>
            <select
              className="service-select"
              aria-label="Sélectionnez un service"
            >
              <option>Tous les services</option>
            </select>
          </div>
          <select className="city-select" aria-label="Sélectionnez une ville">
            <option>Toutes les villes</option>
          </select>
          <button className="search-button">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/843e3c30dd0675c14eed827c8997640bbb54fae0f913329a5ed4a4bb4214a584?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
              alt=""
              className="search-icon"
            />
            <span>Trouver</span>
          </button>
        </div>
      </div>
    </section>
  );
};

export default FindTherapist;
