/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Footer = () => {
  const companyLinks = [
    "À propos",
    "Mentions légales",
    "Protection des données",
    "Politique publicitaire",
    "Politique de cookies",
    "Comment nous vous montrons les résultats",
    "Opinions",
  ];

  const professionalLinks = [
    "Plan Premium",
    "Ajoutez votre cabinet",
    "Connexion professionnels",
    "Annoncez-vous",
    "Avez-vous besoin d'aide ?",
  ];

  const latestOffices = [
    "Veronique Macheix",
    "Nadra Rouzeik",
    "Gilles de la Londe Aurore",
    "Julia Radoszycki",
    "Ludivine Noirault",
  ];

  const topCities = [
    "Psychologues Paris",
    "Psychologues Gironde",
    "Psychologues Bouches-du-Rhône",
    "Psychologues Rhône",
    "Psychologues Haute-Garonne",
  ];

  const latestSearches = [
    "Psychothérapie",
    "Psychologie enfant",
    "Psychanalyse",
    "Thérapie de couple",
  ];

  return (
    <footer className="main-footer">
      <div className="footer-content">
        <div className="footer-columns">
          <div className="footer-column">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/0f9bc6aae80fcabc97dba7a9e4645b4fbf0e9097b386769bf4abce07c6455680?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
              alt="Company Logo"
              className="footer-logo"
            />
            <nav className="footer-nav">
              <h3 className="visually-hidden">Company Information</h3>
              <ul className="footer-list">
                {companyLinks.map((link, index) => (
                  <li key={index}>
                    <a href="#">{link}</a>
                  </li>
                ))}
              </ul>
            </nav>
            <nav className="footer-nav">
              <h3 className="visually-hidden">Professional Services</h3>
              <ul className="footer-list">
                {professionalLinks.map((link, index) => (
                  <li key={index}>
                    <a href="#">{link}</a>
                  </li>
                ))}
              </ul>
            </nav>
          </div>
          <div className="footer-column">
            <nav className="footer-nav">
              <h3>Derniers cabinets</h3>
              <ul className="footer-list">
                {latestOffices.map((office, index) => (
                  <li key={index}>
                    <a href="#">{office}</a>
                  </li>
                ))}
              </ul>
            </nav>
            <nav className="footer-nav">
              <h3>Top villes</h3>
              <ul className="footer-list">
                {topCities.map((city, index) => (
                  <li key={index}>
                    <a href="#">{city}</a>
                  </li>
                ))}
              </ul>
            </nav>
            <nav className="footer-nav">
              <h3>Dernières recherches</h3>
              <ul className="footer-list footer-list-horizontal">
                {latestSearches.map((search, index) => (
                  <li key={index}>
                    <a href="#">{search}</a>
                  </li>
                ))}
              </ul>
            </nav>
          </div>
        </div>
        <div className="social-links">
          <span>Suivez-nous:</span>
          <a href="#" aria-label="Facebook">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/369dab630d9ea82730bab0dab753397698d074e62a584e5f80a131e57c200c39?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
              alt=""
              className="social-icon"
            />
          </a>
          <a href="#" aria-label="Twitter">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/f603cbd3f5babd78bf42bbc257b61ed6e00f31d139a88daca83f4deabcc811cf?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
              alt=""
              className="social-icon"
            />
          </a>
        </div>
      </div>
      <div className="copyright">
        © 2005 - 2024 GoodMental.fr Tous droits réservés. Mise à jour: October
        2024
      </div>
    </footer>
  );
};

export default Footer;
