/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Navigation from "./Navigation";

const Header = () => {
  return (
    <header className="main-header">
      <div className="header-content">
        <div className="logo-nav-wrapper">
          <div className="logo-container">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/2e98c7cf108677b23f1124c495b30d603749fa9b6e38e01397be0d2088141075?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
              alt="Company Logo"
              className="logo-image"
            />
          </div>
          <Navigation />
        </div>
      </div>
    </header>
  );
};

export default Header;
