/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import QuickTest from "./QuickTest";
import FindTherapist from "./FindTherapist";
import Footer from "./Footer";

const LayoutUser = () => {
  return (
    <div className="layout">
      <Header />
      <main>
        <QuickTest />
        <FindTherapist />
      </main>
      <Footer />
      <style jsx>{`
        .layout {
          max-width: none !important;
        }
        .main-header {
          background-color: #fff;
          box-shadow: 0 1px 2px 2px rgba(123, 123, 123, 0.08);
          border-top: 6px solid #62b6b7;
        }
        .header-content {
          display: flex;
          flex-direction: column;
          align-items: center;
          padding: 0 70px;
          max-width: 1247px;
          margin: 0 auto;
        }
        .logo-nav-wrapper {
          display: flex;
          width: 100%;
          gap: 20px;
        }
        .logo-container {
          width: 16%;
        }
        .logo-image {
          width: 231px;
          max-width: 100%;
          aspect-ratio: 1.83;
          object-fit: contain;
        }
        .main-navigation {
          display: flex;
          width: 84%;
          justify-content: space-between;
          align-items: center;
          margin-top: 77px;
          padding: 21px 20px 21px 80px;
          font: 400 16px/1.4 Hind, sans-serif;
          color: #243953;
        }
        .nav-list {
          display: flex;
          gap: 32px;
          list-style-type: none;
          padding: 0;
          margin: 0;
        }
        .nav-item {
          cursor: pointer;
        }
        .about-section {
          display: flex;
          align-items: center;
          gap: 5px;
        }
        .about-icon {
          width: 10px;
          height: 8px;
        }
        .pro-space {
          display: flex;
          align-items: center;
          gap: 8px;
          color: #1db9b4;
          font-weight: 600;
        }
        .pro-icon {
          width: 21px;
          height: 18px;
        }
        .dropdown-icon {
          width: 10px;
          height: 16px;
        }
        .quick-test {
          background-color: #fff;
          padding: 69px 0;
          max-width: 1261px;
          margin: 18px auto 0;
          font-family: Hind, sans-serif;
          color: #243953;
        }
        .test-title {
          font-size: 52px;
          font-weight: 600;
          line-height: 1;
          margin-bottom: 34px;
        }
        .test-description {
          color: #476581;
          font-size: 16px;
          line-height: 24px;
          margin-bottom: 36px;
        }
        .test-form {
          background-color: #f0f3f8;
          border-radius: 8px;
          padding: 10px 36px 59px;
        }
        .form-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 63px;
        }
        .question-label {
          font-size: 24px;
          line-height: 1;
          font-weight: 600;
        }
        .question-number {
          font-size: 52px;
          line-height: 1;
          font-weight: 600;
        }
        .question-text {
          font-size: 20px;
          line-height: 1;
          font-weight: 600;
          margin-bottom: 66px;
        }
        .radio-group {
          display: flex;
          flex-direction: column;
          gap: 20px;
        }
        .radio-option {
          display: flex;
          align-items: center;
          gap: 21px;
          font-size: 20px;
          line-height: 1;
        }
        .submit-button {
          background-color: #1db9b4;
          color: #fff;
          border: none;
          border-radius: 4px;
          padding: 18px 70px;
          font-size: 16px;
          line-height: 1;
          cursor: pointer;
          margin-top: 110px;
        }
        .find-therapist {
          background-color: #fce0d2;
          padding: 92px 80px;
          margin-top: 108px;
        }
        .content-wrapper {
          max-width: 1210px;
          margin: 0 auto;
        }
        .section-title {
          color: #075a8b;
          text-align: center;
          font: 600 50px/1.2 Montserrat, -apple-system, Roboto, Helvetica,
            sans-serif;
          margin-bottom: 25px;
        }
        .section-description {
          color: #237db1;
          text-align: center;
          font: 300 21px/2 Hind, sans-serif;
          margin-bottom: 45px;
        }
        .search-container {
          background-color: #fff;
          border-radius: 4px;
          box-shadow: 5px 10px 20px rgba(36, 57, 83, 0.15);
          padding: 16px 20px;
          display: flex;
          gap: 20px;
        }
        .search-options {
          display: flex;
          flex-direction: column;
          width: 41%;
        }
        .therapy-type {
          display: flex;
          gap: 32px;
          margin-bottom: 16px;
        }
        .therapy-button {
          display: flex;
          align-items: center;
          gap: 7px;
          padding: 11px 20px;
          border-radius: 34px;
          font-weight: 600;
          cursor: pointer;
        }
        .therapy-button.online {
          background-color: #f4f6f8;
          color: #243953;
        }
        .therapy-button.in-person {
          background-color: #fff;
          border: 2px solid #d0d6e1;
          box-shadow: 0 4px 8px rgba(12, 116, 112, 0.15);
        }
        .therapy-icon {
          width: 19px;
          height: 13px;
        }
        .service-select,
        .city-select {
          border: 1px solid #d0d6e1;
          border-radius: 4px;
          padding: 17px;
          font-size: 16px;
          color: #617d97;
        }
        .city-select {
          width: 41%;
        }
        .search-button {
          background-color: #0579c7;
          color: #fff;
          border: none;
          border-radius: 4px;
          padding: 16px 39px;
          font-size: 18px;
          display: flex;
          align-items: center;
          gap: 9px;
          cursor: pointer;
        }
        .search-icon {
          width: 17px;
          height: 18px;
        }
        .main-footer {
          background-color: #2d2d2d;
          color: #848484;
          font: 400 14px/1.4 Hind, sans-serif;
          padding-bottom: 52px;
        }
        .footer-content {
          max-width: 1126px;
          margin: 0 auto;
          padding-top: 42px;
        }
        .footer-columns {
          display: flex;
          gap: 20px;
        }
        .footer-column {
          flex: 1;
        }
        .footer-logo {
          width: 157px;
          margin-bottom: 23px;
        }
        .footer-nav {
          margin-bottom: 26px;
        }
        .footer-list {
          list-style-type: none;
          padding: 0;
          margin: 0;
        }
        .footer-list li {
          margin-bottom: 23px;
        }
        .footer-list a {
          color: inherit;
          text-decoration: none;
        }
        .footer-list-horizontal {
          display: flex;
          flex-wrap: wrap;
          gap: 25px;
        }
        .social-links {
          display: flex;
          align-items: center;
          gap: 12px;
          margin-top: 14px;
        }
        .social-icon {
          width: 30px;
          height: 30px;
        }
        .copyright {
          background-color: #000;
          color: #fff;
          text-align: center;
          padding: 28px 0;
          margin-top: 24px;
        }
        @media (max-width: 991px) {
          .header-content {
            padding: 0 20px;
          }
          .logo-nav-wrapper {
            flex-direction: column;
          }
          .logo-container,
          .main-navigation {
            width: 100%;
          }
          .main-navigation {
            margin-top: 40px;
            padding-left: 20px;
          }
          .test-title {
            font-size: 40px;
          }
          .question-number {
            font-size: 40px;
          }
          .submit-button {
            margin-top: 40px;
            padding: 18px 20px;
          }
          .find-therapist {
            padding: 40px 20px;
            margin-top: 40px;
          }
          .section-title {
            font-size: 40px;
          }
          .search-container {
            flex-direction: column;
          }
          .search-options,
          .city-select {
            width: 100%;
          }
          .footer-columns {
            flex-direction: column;
          }
        }
        .visually-hidden {
          position: absolute;
          width: 1px;
          height: 1px;
          margin: -1px;
          padding: 0;
          overflow: hidden;
          clip: rect(0, 0, 0, 0);
          white-space: nowrap;
          border: 0;
        }
      `}</style>
    </div>
  );
};

export default LayoutUser;
