/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Navigation = () => {
  const navItems = [
    { text: "Nos questionnaires", className: "nav-item" },
    { text: "Chat", className: "nav-item" },
    { text: "Dashboard", className: "nav-item" },
    { text: "Notification", className: "nav-item notification" },
    { text: "FAQ", className: "nav-item faq" },
  ];

  return (
    <nav className="main-navigation">
      <ul className="nav-list">
        {navItems.map((item, index) => (
          <li key={index} className={item.className}>
            {item.text}
          </li>
        ))}
      </ul>
      <div className="about-section">
        <span>A propos</span>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/9401071b630e632dcd48a29fc3ec9e8862dcf3930e1e113cd2ee47e3aab589f6?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
          alt=""
          className="about-icon"
        />
      </div>
      <div className="pro-space">
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/0a0651e0caa3258795e5bf0dba446be3bd5c7850546aaf67eb685ce7fa5cc7f9?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
          alt=""
          className="pro-icon"
        />
        <span className="pro-text">Espace professionnel</span>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/08703b2297ea79d844c90aeedb21aeb20c0f39764108d65de53c9114ec095d58?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
          alt=""
          className="dropdown-icon"
        />
      </div>
    </nav>
  );
};

export default Navigation;
