/**
 * This code was generated by Builder.io.
 */
import React from "react";

const QuickTest = () => {
  return (
    <section className="quick-test">
      <h2 className="test-title">Test rapide</h2>
      <p className="test-description">
        Ce questionnaire est destiné à une première évaluation rapide de l'état
        mental de l'utilisateur. Les questions sont basiques mais couvrent les
        principales dimensions du bien-être mental.
      </p>
      <form className="test-form">
        <div className="form-header">
          <label htmlFor="test-question" className="question-label">
            Thèmes couverts : Stress, Sommeil, Humeur, Énergie
          </label>
          <span className="question-number">1/10</span>
        </div>
        <fieldset>
          <legend className="question-text">
            Comment évaluez-vous votre niveau de stress actuel ?
          </legend>
          <div className="radio-group">
            <div className="radio-option">
              <input
                type="radio"
                id="very-stressed"
                name="stress-level"
                value="very-stressed"
              />
              <label htmlFor="very-stressed">Très stressé</label>
            </div>
            <div className="radio-option">
              <input
                type="radio"
                id="somewhat-stressed"
                name="stress-level"
                value="somewhat-stressed"
              />
              <label htmlFor="somewhat-stressed">Un peu stressé</label>
            </div>
            <div className="radio-option">
              <input
                type="radio"
                id="not-stressed"
                name="stress-level"
                value="not-stressed"
              />
              <label htmlFor="not-stressed">Pas stressé du tout</label>
            </div>
          </div>
        </fieldset>
        <button type="submit" className="submit-button">
          Valider
        </button>
      </form>
    </section>
  );
};

export default QuickTest;
