/**
 * This code was generated by Builder.io.
 */
import React from "react";
import LoginForm from "./LoginForm";
import FeatureList from "./FeatureList";
import styles from "./LoginPage.module.css";
import NavBar from "../NavBar";
import Footer from "../Footer/Footer";

function LoginPage() {
  return (
    <div>
    <NavBar/>
    <main className={styles.loginPage}>
      <div className={styles.container}>
        <section className={styles.featureSection}>
          <FeatureList />
        </section>
        <section className={styles.loginSection}>
          <LoginForm />
        </section>
      </div>
    </main>
    <Footer/>
    </div>
  );
}

export default LoginPage;
