/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Copyright = () => {
  return (
    <div className="copyright">
      © 2005 - 2024 GoodMental.fr Tous droits réservés. Mise à jour: October
      2024
      <style jsx>{`
        .copyright {
          background-color: #000;
          color: #fff;
          text-align: center;
          padding: 28px 20px;
          font-size: 14px;
        }
      `}</style>
    </div>
  );
};

export default Copyright;
