/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import FooterColumn from './FooterColumn';
import SocialLinks from './SocialLinks';
import Copyright from './Copyright';

const Footer = () => {
  const aboutLinks = [
    { text: 'À propos' },
    { text: 'Mentions légales' },
    { text: 'Protection des données' },
    { text: 'Politique publicitaire' },
    { text: 'Politique de cookies' },
    { text: 'Comment nous vous montrons les résultats', className: 'two-line' },
    { text: 'Opinions' }
  ];

  const planLinks = [
    { text: 'Plan Premium' },
    { text: 'Ajoutez votre cabinet' },
    { text: 'Connexion professionnels' },
    { text: 'Annoncez-vous' },
    { text: 'Avez-vous besoin daide ?' }
  ];

  const latestOffices = [
    'Veronique Macheix',
    'Nadra Rouzeik',
    'Gilles de la Londe Aurore',
    'Julia Radoszycki',
    'Ludivine Noirault'
  ];

  const topCities = [
    'Psychologues Paris',
    'Psychologues Gironde',
    'Psychologues Bouches-du-Rhône',
    'Psychologues Rhône',
    'Psychologues Haute-Garonne'
  ];

  const latestSearches = [
    'Psychothérapie',
    'Psychologie enfant',
    'Psychanalyse',
    'Thérapie de couple'
  ];

  return (
    <footer className="footer">
      <div className="footer-content">
        <div className="footer-columns">
          <FooterColumn
            logo="https://cdn.builder.io/api/v1/image/assets/TEMP/0f9bc6aae80fcabc97dba7a9e4645b4fbf0e9097b386769bf4abce07c6455680?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
            title="À propos"
            links={aboutLinks}
          />
          <FooterColumn title="Plan Premium" links={planLinks} />
          <div className="footer-main-content">
            <section className="latest-offices">
              <h2 className="section-title">Derniers cabinets</h2>
              <ul className="office-list">
                {latestOffices.map((office, index) => (
                  <li key={index} className="office-item">{office}</li>
                ))}
              </ul>
            </section>
            <section className="top-cities">
              <h2 className="section-title">Top villes</h2>
              <ul className="city-list">
                {topCities.map((city, index) => (
                  <li key={index} className="city-item">{city}</li>
                ))}
              </ul>
            </section>
            <section className="latest-searches">
              <h2 className="section-title">Dernières recherches</h2>
              <ul className="search-list">
                {latestSearches.map((search, index) => (
                  <li key={index} className="search-item">{search}</li>
                ))}
              </ul>
            </section>
          </div>
        </div>
        <SocialLinks />
      </div>
      <Copyright />
      <style jsx>{`
        .footer {
          background-color: #2d2d2d;
          color: #848484;
          font-family: Hind, sans-serif;
          font-size: 14px;
          line-height: 1.4;
        }
        .footer-content {
          max-width: 1126px;
          margin: 0 auto;
          padding: 40px 20px;
        }
        .footer-columns {
          display: flex;
          flex-wrap: wrap;
          gap: 20px;
        }
        .footer-main-content {
          flex: 1;
          display: flex;
          flex-direction: column;
          gap: 40px;
        }
        .section-title {
          color: #fff;
          margin-bottom: 20px;
        }
        .office-list,
        .city-list,
        .search-list {
          list-style-type: none;
          padding: 0;
        }
        .office-item,
        .city-item,
        .search-item {
          margin-bottom: 10px;
        }
        @media (max-width: 991px) {
          .footer-columns {
            flex-direction: column;
          }
        }
      `}</style>
    </footer>
  );
};

export default Footer;
