/**
 * This code was generated by Builder.io.
 */
import React from "react";

const FooterColumn = ({ logo, title, links }) => {
  return (
    <div className="footer-column">
      {logo && <img src={logo} alt="Logo" className="footer-logo" />}
      <h2 className="column-title">{title}</h2>
      <nav>
        <ul className="footer-links">
          {links.map((link, index) => (
            <li key={index} className={`footer-link ${link.className || ""}`}>
              {link.text}
            </li>
          ))}
        </ul>
      </nav>
      <style jsx>{`
        .footer-column {
          flex: 1;
          min-width: 200px;
        }
        .footer-logo {
          width: 157px;
          height: auto;
          margin-bottom: 20px;
        }
        .column-title {
          color: #fff;
          margin-bottom: 20px;
        }
        .footer-links {
          list-style-type: none;
          padding: 0;
        }
        .footer-link {
          margin-bottom: 10px;
        }
        .two-line {
          line-height: 20px;
        }
      `}</style>
    </div>
  );
};

export default FooterColumn;
