/**
 * This code was generated by Builder.io.
 */
import React from "react";

const SocialLinks = () => {
  return (
    <div className="social-links">
      <span className="follow-text">Suivez-nous:</span>
      <a href="#" aria-label="Facebook">
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/01fcddfdac19bb5fdbb09b0321f81faf19c59266cb447374ab899fcc0c74b095?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
          alt=""
          className="social-icon"
        />
      </a>
      <a href="#" aria-label="Twitter">
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/3aa1536b2e4c31090e0edbfde029d241c96e7ae714868e7802e0867318ebc372?placeholderIfAbsent=true&apiKey=4af6d38b4e1f414ca48eef301541d7ae"
          alt=""
          className="social-icon"
        />
      </a>
      <style jsx>{`
        .social-links {
          display: flex;
          align-items: center;
          gap: 12px;
          margin-top: 20px;
        }
        .follow-text {
          color: #fff;
        }
        .social-icon {
          width: 30px;
          height: 30px;
        }
      `}</style>
    </div>
  );
};

export default SocialLinks;
